[project]
name = "colawater-toolbox"
version = "v3.6.0"
authors = [{ name = "felix", email = "sfx86@users.noreply.github.com" }]
description = "ArcGIS geoprocessing tools for Columbia Water"
readme = "README.md"
requires-python = ">=3.9"

[tool.mypy]
python_version = 3.9
files = "./src"
strict = true
enable_error_code = "ignore-without-code"

[[tool.mypy.overrides]]
module = "arcpy.*"
ignore_missing_imports = true


[tool.git-cliff.changelog]
header = """
# Changelog
"""
body = """
{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}](<REPO>/compare/{{ previous.version }}..{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""
trim = true
footer = "<!-- generated by git-cliff -->"
postprocessors = [
    { pattern = '<REPO>', replace = "https://github.com/sfx86/colawater-toolbox" },
]

[tool.git-cliff.git]
conventional_commits = true
filter_unconventional = true
tag_pattern = 'v[0-9]*'
sort_commits = "oldest"
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^doc", group = "Documentation" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactor" },
    { message = "^style", group = "Styling" },
    { message = "^test", group = "Testing" },
    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "^chore\\(deps\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^chore|ci", group = "Miscellaneous Tasks" },
    { message = "^revert", group = "Revert" },
]
