name: Create release

on: 
  push:
    tags:
      - "v*"
        
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Archive src
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: "zip"
        filename: "colawater-toolbox.zip"
        directory: "src/"
        path: "."
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "src/colawater-toolbox.zip"
        bodyFile: "CHANGELOG.md"